name: Build Docs and Deploy

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -e .

      - name: Generate pdoc documentation
        run: pdoc -o ./docs/documents ./nlqk

      - name: Build Jekyll site
        run: |
          gem install bundler jekyll github-pages
          bundle install
          bundle exec jekyll build

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site  # Assuming Jekyll builds to the _site directory
