name: code documentation
# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -e .
      #- name: Install pdoc
      #  run: pip install pdoc
      - run: pdoc -o docs/documentation/ nlqk/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs/documentation'
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./docs/documentation #  Your documentation output directory

